import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  gameSidebar: [
    {
      type: 'doc',
      id: 'game/index',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Builds',
      items: [
        {
          type: 'autogenerated',
          dirName: 'game/builds',
        },
      ],
    },
  ],
};

export default sidebars;
